# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: producto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'producto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducto.proto\x12\x08producto\"F\n\x0fProductoRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x01\"\xa2\x01\n\x15UpdateProductoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x01\x12\x15\n\rupdate_nombre\x18\x05 \x01(\x08\x12\x1a\n\x12update_descripcion\x18\x06 \x01(\x08\x12\x15\n\rupdate_precio\x18\x07 \x01(\x08\"\x18\n\nProductoId\x12\n\n\x02id\x18\x01 \x01(\x05\"S\n\x10ProductoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x01\"=\n\x0cProductoList\x12-\n\tproductos\x18\x01 \x03(\x0b\x32\x1a.producto.ProductoResponse\"\x07\n\x05\x45mpty\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa7\x03\n\x0fProductoService\x12G\n\x0e\x43reateProducto\x12\x19.producto.ProductoRequest\x1a\x1a.producto.ProductoResponse\x12\x38\n\rListProductos\x12\x0f.producto.Empty\x1a\x16.producto.ProductoList\x12?\n\x0bGetProducto\x12\x14.producto.ProductoId\x1a\x1a.producto.ProductoResponse\x12M\n\x0eUpdateProducto\x12\x1f.producto.UpdateProductoRequest\x1a\x1a.producto.ProductoResponse\x12@\n\x0e\x44\x65leteProducto\x12\x14.producto.ProductoId\x1a\x18.producto.DeleteResponse\x12?\n\x14ListProductosGraphQL\x12\x0f.producto.Empty\x1a\x16.producto.ProductoListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'producto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTOREQUEST']._serialized_start=28
  _globals['_PRODUCTOREQUEST']._serialized_end=98
  _globals['_UPDATEPRODUCTOREQUEST']._serialized_start=101
  _globals['_UPDATEPRODUCTOREQUEST']._serialized_end=263
  _globals['_PRODUCTOID']._serialized_start=265
  _globals['_PRODUCTOID']._serialized_end=289
  _globals['_PRODUCTORESPONSE']._serialized_start=291
  _globals['_PRODUCTORESPONSE']._serialized_end=374
  _globals['_PRODUCTOLIST']._serialized_start=376
  _globals['_PRODUCTOLIST']._serialized_end=437
  _globals['_EMPTY']._serialized_start=439
  _globals['_EMPTY']._serialized_end=446
  _globals['_DELETERESPONSE']._serialized_start=448
  _globals['_DELETERESPONSE']._serialized_end=498
  _globals['_PRODUCTOSERVICE']._serialized_start=501
  _globals['_PRODUCTOSERVICE']._serialized_end=924
# @@protoc_insertion_point(module_scope)
